/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file implements the functions for encoding and decoding the
 * 'mviz_msg' message type. See VizMsg.h for more details.
 */

#include <message.h>
#include "VizMsg.h"

uint16_t MVIZ_H_version_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 0, 16);
}

void MVIZ_H_version_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 0, 16, value);
}

uint16_t MVIZ_H_interval_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 16, 16);
}

void MVIZ_H_interval_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 16, 16, value);
}

uint16_t MVIZ_H_origin_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 32, 16);
}

void MVIZ_H_origin_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 32, 16, value);
}

uint16_t MVIZ_H_count_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 48, 16);
}

void MVIZ_H_count_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 48, 16, value);
}

uint16_t MVIZ_H_parent_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 64, 16);
}

void MVIZ_H_parent_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 64, 16, value);
}

uint16_t MVIZ_H_etx_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 80, 16);
}

void MVIZ_H_etx_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 80, 16, value);
}

uint16_t MVIZ_H_forward_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 96, 16);
}

void MVIZ_H_forward_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 96, 16, value);
}

uint16_t MVIZ_H_link_route_addr_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 112, 16);
}

void MVIZ_H_link_route_addr_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 112, 16, value);
}

